### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by rifsxd** [statulr/aurc#8]
hey bro i havent checked on your repo of aurc since i left aurc, what i see here is there is no attribution or crediting me about this anywhere since 90% of the code is mine and this is kinda inappropriate so what i suggest you doing is give proper credits or just fork my aurc repo and then commit your aurc code from local.

**Comment by rifsxd** [comment]
![Screenshot from 2023-11-26 15-28-36](https://github.com/statulr/aurc/assets/33044977/9b043b3b-63b5-43d0-a2b9-5dc3bfddc3aa)


my name should be in the copyright along side yours

**Comment by statulr** [comment]
> ![Screenshot from 2023-11-26 15-28-36](https://private-user-images.githubusercontent.com/33044977/285641274-9b043b3b-63b5-43d0-a2b9-5dc3bfddc3aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwMTczNTMsIm5iZiI6MTcwMTAxNzA1MywicGF0aCI6Ii8zMzA0NDk3Ny8yODU2NDEyNzQtOWIwNDNiM2ItNjNiNS00M2QwLWEyYjktNWRjM2JmZGRjM2FhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDE2NDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhMDQ5NzQ5MGE0YTUyNjMyNDg5ZDQzZjdhNzUwNjZlZDMwNzUwYmRiYjAyZGE3MTk5YzI1OWVjMTM5YzNkYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.71npK7DjDyqH30tnsqAZRu8YeH6SQIjh8-tAlWjugsI)
> 
> my name should be in the copyright along side yours

You randomely blocked me after saying you didn't want to work with me anymore and that was quite rude, I changed the code a lot since you left, you have your own fork, this isn't your code, you have your version remember :)

**Comment by statulr** [comment]
> hey bro i havent checked on your repo of aurc since i left aurc, what i see here is there is no attribution or crediting me about this anywhere since 90% of the code is mine and this is kinda inappropriate so what i suggest you doing is give proper credits or just fork my aurc repo and then commit your aurc code from local.

Your repo doesn't attribute me either, you chose to leave and block me. That was your choice, after I made the org you said I could have it and I continued it a lot time.
